- ansible.builtin.command: "yum update"
- ansible.builtin.command: "yum install nfs-utils"


- ansible.builtin.command: "mkdir -p /opt/nfsdata"
- ansible.builtin.command: "chown nobody:nobody /opt/nfsdata"
- ansible.builtin.lineinfile: path="/etc/exports" line="/opt/nfsdata	192.168.1.100(rw,sync,no_root_squash,no_subtree_check)"

- ansible.builtin.command: "systemctl restart nfs-server"

- ansible.builtin.command: "firewall-cmd --permanent --add-service=nfs"
- ansible.builtin.command: "firewall-cmd --permanent --add-service=rpc-bind"
- ansible.builtin.command: "firewall-cmd --permanent --add-service=mountd"
- ansible.builtin.command: "firewall-cmd --permanent --add-service=reload"
