- ansible.builtin.command: "apt-get update"
- ansible.builtin.command: "apt-get install nfs-common"

- ansible.builtin.command: "systemctl stop ufw"
- ansible.builtin.command: "systemctl disable ufw"

- ansible.builtin.command: "mkdir -p /nfsdata"
- ansible.builtin.command: "mount 192.168.1.99:/opt/nfsdata /nfsdata"

- ansible.builtin.lineinfile: path="/etc/fstab" line="192.168.1.99:/opt/nfsdata	/nfsdata	nfs	default	0	0"
