- hosts: nfs-server
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - include: tasks/nfs/nfs-server.yaml

- hosts: nfs-client
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - include: tasks/nfs/nfs-client.yaml
